[package]
name = "pldm-fw"
version = "0.1.0"
edition = "2021"

[dependencies]
pldm = { workspace = true }
mctp = { workspace = true }
mctp-linux = { workspace = true }
nom = "7.1"
itertools = "0.10"
chrono = "0.4"
enumset = "1.1"
uuid = { version = "1.3", features = ["v1"] }
thiserror = "1.0"
argh = "0.1.12"
anyhow = "1.0.80"
log = "0.4"
env_logger = "0.11.3"
crc = "3.0"
